"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import styles from "../live.module.css";

type Lot={id:string;playerName:string;status:string;startingBid:number;bidIncrement:number;currentBid:number;currentBidderId:string|null;sortOrder:number};
type State={auction:{id:string;name:string;status:string};admin:boolean;viewerBidderId:string|null;viewerPurse:{initialPurse:number;spentPurse:number;status:string}|null;activeLot:Lot|null;bids:Array<{id:string;bidderName:string;amount:number;sequence:number}>;teams:Array<{id:string;name:string;initialPurse:number;spentPurse:number;active:boolean}>};

export default function LiveAuctionPage(){
  const {user,loading}=useAuth(); const params=useParams<{auctionId:string}>(); const router=useRouter(); const id=params.auctionId;
  const [state,setState]=useState<State|null>(null); const [lots,setLots]=useState<Lot[]>([]); const [bid,setBid]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const token=useCallback(async()=>user?user.getIdToken(true):"",[user]);
  const load=useCallback(async()=>{if(!user)return;try{const t=await token();const [liveRes,lotsRes]=await Promise.all([fetch(`/api/auctions/${id}/live`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch(`/api/auctions/${id}/lots`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})]);const a=await liveRes.json();const l=await lotsRes.json();if(!liveRes.ok)throw new Error(a.error||"Unable to load auction.");setState(a);setLots(l.lots??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load live auction.");}},[user,id,token]);
  useEffect(()=>{if(!loading&&user){const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),2000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};}},[loading,user,load]);
  const active=state?.activeLot; const queued=useMemo(()=>lots.filter(l=>l.status==="queued"),[lots]);
  async function call(path:string,method="POST",body?:unknown){if(!user)return;setBusy(true);setError("");setNotice("");try{const t=await token();const r=await fetch(path,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Action failed.");setNotice("Action completed.");await load();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}}
  async function placeBid(){if(!active)return;const n=Number(bid);if(!Number.isFinite(n)||n<=0){setError("Enter a valid bid.");return;}await call(`/api/auctions/${id}/lots/${active.id}/bids`,"POST",{amount:n});setBid("");}
  if(loading||!user)return <main className={styles.shell}><p>Loading…</p></main>;
  if(!state)return <main className={styles.shell}><div className={styles.error}>{error||"Loading auction…"}</div></main>;
  const nextMinimum=active?Math.max(active.startingBid,active.currentBid>0?active.currentBid+active.bidIncrement:active.startingBid):0;
  return <main className={styles.shell}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Live Auction</p><h1>{state.auction.name}</h1><p className={styles.subtitle}>Real-time auction room with server-validated bidding, purse controls and settlement.</p></div><div className={styles.actions}><button className={styles.secondary} onClick={()=>router.push(`/auctions/${id}/lots`)}>LOT SETUP</button><button className={styles.secondary} onClick={()=>router.push(`/auctions/${id}/teams`)}>TEAMS</button><button className={styles.secondary} onClick={()=>router.back()}>Back</button></div></header>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
    <section className={styles.grid}>
      <div className={styles.card}><p className={styles.eyebrow}>Current lot</p>{active?<><h2>{active.playerName}</h2><div className={styles.metricRow}><div><span>Current bid</span><strong>{active.currentBid||active.startingBid}</strong></div><div><span>Minimum next</span><strong>{nextMinimum}</strong></div><div><span>Status</span><strong>{active.status}</strong></div></div>{state.bids.length>0&&<div className={styles.bids}>{state.bids.slice(0,10).map(b=><div key={b.id}><span>#{b.sequence} {b.bidderName}</span><strong>{b.amount}</strong></div>)}</div>}{state.admin?<div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={()=>call(`/api/auctions/${id}/lots/${active.id}/settle`,"POST",{outcome:"sold"})}>SELL LOT</button><button className={styles.secondary} disabled={busy} onClick={()=>call(`/api/auctions/${id}/lots/${active.id}/settle`,"POST",{outcome:"unsold"})}>UNSOLD</button><button className={styles.secondary} disabled={busy} onClick={()=>call(`/api/auctions/${id}/lots`,"PATCH",{lotId:active.id,status:active.status==="live"?"paused":"live"})}>{active.status==="live"?"PAUSE LOT":"RESUME LOT"}</button></div>:state.viewerBidderId&&state.viewerPurse?.status==="active"?<div className={styles.bidBox}><input type="number" min={nextMinimum} step="1" value={bid} onChange={e=>setBid(e.target.value)} placeholder={String(nextMinimum)}/><button className={styles.primary} disabled={busy} onClick={()=>void placeBid()}>PLACE BID</button><small>Available purse: {state.viewerPurse.initialPurse-state.viewerPurse.spentPurse}</small></div>:<p className={styles.muted}>You are viewing this auction. Bidding is unavailable for your account.</p>}</>:<div className={styles.empty}><h2>No active lot</h2><p>{state.admin?"Start the next queued lot below.":"Waiting for the auction administrator to open the next lot."}</p></div>}</div>
      <aside className={styles.card}><p className={styles.eyebrow}>Auction control</p><div className={styles.metric}><span>Auction status</span><strong>{state.auction.status}</strong></div><div className={styles.metric}><span>Queued lots</span><strong>{queued.length}</strong></div>{state.viewerPurse&&<div className={styles.metric}><span>My available purse</span><strong>{state.viewerPurse.initialPurse-state.viewerPurse.spentPurse}</strong></div>}{state.admin&&<div className={styles.actions}><button className={styles.primary} disabled={busy||!!active||!queued[0]} onClick={()=>queued[0]&&call(`/api/auctions/${id}/lots`,"PATCH",{lotId:queued[0].id,status:"live"})}>START NEXT LOT</button><button className={styles.secondary} disabled={busy||state.auction.status==="ended"} onClick={()=>call(`/api/auctions/${id}/finalize`)}>FINALIZE AUCTION</button><button className={styles.secondary} onClick={()=>router.push(`/auctions/${id}/teams`)}>TEAMS & SQUADS</button></div>}</aside>
    </section>
  </main>;
}
