"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { createAuctionCategory, createPlayer, listAuctionCategories, listAuctionParticipants, listPlayers, registerAuctionParticipant } from "@/lib/participants/repository";
import type { AuctionCategory, AuctionParticipant, Player } from "@/lib/auctions/types";
import styles from "../../auctions/auctions.module.css";

export default function AuctionParticipantsPage() {
  const { user, loading } = useAuth(); const router = useRouter(); const params = useParams<{ auctionId: string }>(); const auctionId = params.auctionId;
  const [players, setPlayers] = useState<Player[]>([]); const [categories, setCategories] = useState<AuctionCategory[]>([]); const [participants, setParticipants] = useState<AuctionParticipant[]>([]);
  const [playerId, setPlayerId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [basePrice, setBasePrice] = useState(""); const [newPlayer, setNewPlayer] = useState(""); const [categoryName, setCategoryName] = useState(""); const [categoryPrice, setCategoryPrice] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");

  async function load() { if (!user) return; try { const [p, c, a] = await Promise.all([listPlayers(user), listAuctionCategories(user, auctionId), listAuctionParticipants(user, auctionId)]); setPlayers(p); setCategories(c.filter((item) => item.active)); setParticipants(a); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load participant configuration."); } }
  useEffect(() => { if (!loading && user) void load(); }, [loading, user, auctionId]);
  useEffect(() => { const selected = categories.find((item) => item.id === categoryId); if (selected && !basePrice) setBasePrice(String(selected.defaultBasePrice)); }, [categoryId, categories, basePrice]);

  async function addPlayer() { if (!user || !newPlayer.trim()) return; setBusy(true); setError(""); try { const created = await createPlayer(user, newPlayer.trim()); setPlayers((current) => [...current, created].sort((a, b) => a.displayName.localeCompare(b.displayName))); setPlayerId(created.id); setNewPlayer(""); setNotice("Player created. Select a category and add the player to this auction."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create player."); } finally { setBusy(false); } }
  async function addCategory() { if (!user) return; const price = Number(categoryPrice); if (!categoryName.trim() || !Number.isFinite(price) || price < 0) { setError("Category name and a valid non-negative base price are required."); return; } setBusy(true); setError(""); try { await createAuctionCategory(user, auctionId, { name: categoryName.trim(), defaultBasePrice: price }); setCategoryName(""); setCategoryPrice(""); await load(); setNotice("Category added to this auction."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create category."); } finally { setBusy(false); } }
  async function addParticipant() { if (!user || !playerId || !categoryId) { setError("Select a player and an auction category."); return; } const price = basePrice === "" ? undefined : Number(basePrice); if (price !== undefined && (!Number.isFinite(price) || price < 0)) { setError("Base price must be a non-negative number."); return; } setBusy(true); setError(""); try { await registerAuctionParticipant(user, auctionId, { playerId, categoryId, basePrice: price }); setPlayerId(""); setCategoryId(""); setBasePrice(""); await load(); setNotice("Player added to this auction with the selected category and base price."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add participant."); } finally { setBusy(false); } }

  if (loading || !user) return <main className={styles.loading}>Loading participants…</main>;
  return <main className={styles.shell}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Auction Platform / Participants</p><h1>Auction participants</h1><p className={styles.subtitle}>Configure who is participating in this auction. Categories and base prices belong to this auction, not to the player.</p></div><div className={styles.headerActions}><button className={styles.secondaryButton} onClick={() => router.push("/auctions")}>Back</button></div></header>
    <section className={styles.editor}>
      {error && <div className={styles.error} role="alert">{error}</div>}{notice && <div className={styles.notice} role="status">{notice}</div>}
      <div className={styles.adminPanel}><div><p className={styles.eyebrow}>Auction categories</p><h2>Categories & base prices</h2><p>These values are owned by this auction. The same player can have a different category and base price in another auction.</p></div><div className={styles.formGrid}><label>CATEGORY NAME<input value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="Platinum" /></label><label>DEFAULT BASE PRICE<input type="number" min="0" step="1" value={categoryPrice} onChange={(e) => setCategoryPrice(e.target.value)} placeholder="10" /></label></div><button className={styles.primaryButton} disabled={busy} onClick={addCategory}>ADD CATEGORY</button><div className={styles.adminList}>{categories.length === 0 ? <p>No categories configured for this auction.</p> : categories.map((category) => <div key={category.id} className={styles.adminOption}><span><strong>{category.name}</strong><small>Default base price: {category.defaultBasePrice} points</small></span></div>)}</div></div>
      <div className={styles.adminPanel}><div><p className={styles.eyebrow}>Register participant</p><h2>Add player to this auction</h2><p>The player record stays generic. Category and base price are assigned only here, for this auction.</p></div><label>PLAYER<select value={playerId} onChange={(e) => setPlayerId(e.target.value)}><option value="">Select a player</option>{players.map((player) => <option key={player.id} value={player.id}>{player.displayName}</option>)}</select></label><div className={styles.formGrid}><label>NEW PLAYER<input value={newPlayer} onChange={(e) => setNewPlayer(e.target.value)} placeholder="Player name" /></label><div><span className={styles.eyebrow}>&nbsp;</span><button className={styles.secondaryButton} disabled={busy || !newPlayer.trim()} onClick={addPlayer}>CREATE PLAYER</button></div></div><div className={styles.formGrid}><label>CATEGORY<select value={categoryId} onChange={(e) => { setCategoryId(e.target.value); setBasePrice(""); }}><option value="">Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name} — {category.defaultBasePrice} points</option>)}</select></label><label>BASE PRICE<input type="number" min="0" step="1" value={basePrice} onChange={(e) => setBasePrice(e.target.value)} placeholder="Uses category default" /></label></div><button className={styles.primaryButton} disabled={busy} onClick={addParticipant}>ADD TO AUCTION</button></div>
      <div className={styles.listPanel}><div className={styles.listHeader}><span>REGISTERED IN THIS AUCTION</span><b>{participants.length}</b></div>{participants.length === 0 ? <div className={styles.empty}>No players have been added to this auction yet.</div> : participants.map((participant) => <div key={participant.id} className={styles.auctionItem}><span className={styles.itemTop}><strong>{participant.playerName}</strong><em>{participant.status}</em></span><span className={styles.itemBottom}>Category: {participant.categoryName}</span><span className={styles.itemBottom}>Base price: {participant.basePrice} points</span></div>)}</div>
    </section>
  </main>;
}
