"use client";

import { useCallback, useEffect, useState } from "react";
import type { User } from "firebase/auth";
import styles from "./auctions.module.css";

type Candidate = { userId: string; displayName: string; email: string; role: string; assigned: boolean; initialPurse: number; status: string };
type Props = { user: User; auctionId: string };
export function AuctionBiddersSection({ user, auctionId }: Props) {
  const [users,setUsers]=useState<Candidate[]>([]);const[selected,setSelected]=useState<Record<string,number>>({});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const token=await user.getIdToken(true);const r=await fetch(`/api/auctions/${auctionId}/bidder-assignments`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load bidders.");const list=(d.users??[]) as Candidate[];setUsers(list);setSelected(Object.fromEntries(list.filter(x=>x.assigned).map(x=>[x.userId,x.initialPurse])));}catch(e){setError(e instanceof Error?e.message:"Unable to load bidders.");}finally{setLoading(false);}},[auctionId,user]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
  function toggle(id:string,checked:boolean){setSelected(current=>{if(checked)return{...current,[id]:current[id]??0};const next={...current};delete next[id];return next;});}
  async function save(){setBusy(true);setError("");setNotice("");try{const token=await user.getIdToken(true);const r=await fetch(`/api/auctions/${auctionId}/bidder-assignments`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({bidders:Object.entries(selected).map(([userId,initialPurse])=>({userId,initialPurse}))})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save bidders.");setNotice("Auction bidders updated successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save bidders.");}finally{setBusy(false);}}
  return <section className={styles.configSection}><div className={styles.configHeader}><div><p className={styles.eyebrow}>Auction setup</p><h2>Bidders</h2><p>Assign any registered non-Super-Admin user as a bidder for this auction. This assignment does not change the user’s global role.</p></div></div>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{loading?<div className={styles.empty}>Loading registered users…</div>:!users.length?<div className={styles.empty}>No eligible registered users are available.</div>:<div className={styles.bidderList}>{users.map(item=><label className={styles.bidderOption} key={item.userId}><input type="checkbox" checked={item.userId in selected} onChange={e=>toggle(item.userId,e.target.checked)}/><span className={styles.bidderIdentity}><strong>{item.displayName||"Unnamed user"}</strong><small>{item.email} · {item.role}</small></span>{item.userId in selected&&<span className={styles.bidderPurse}><small>INITIAL PURSE</small><input type="number" min="0" value={selected[item.userId]??0} onChange={e=>setSelected(current=>({...current,[item.userId]:Number(e.target.value)}))} onClick={e=>e.stopPropagation()}/></span>}</label>)}</div>}<button className={styles.primaryButton} disabled={busy||loading} onClick={()=>void save()}>{busy?"SAVING…":"SAVE BIDDERS"}</button></section>;
}
