"use client";

import { useEffect, useState } from "react";
import { signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import { getFirebaseAuth } from "@/lib/firebase/client";
import { createParticipantAccount } from "@/lib/participants/repository";
import styles from "./participant.module.css";

type Auction = { id: string; name: string; status: string; categoryName?: string; basePrice?: number; minimumBasePrice?: number; participantStatus?: string };
type Participant = { id: string; displayName: string; userId?: string | null; email?: string };

export default function ParticipantPage() {
  const { user, loading } = useAuth(); const router = useRouter();
  const [roles, setRoles] = useState<string[]>([]); const [auctions, setAuctions] = useState<Auction[]>([]); const [participants, setParticipants] = useState<Participant[]>([]);
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [expertise, setExpertise] = useState(""); const [photo, setPhoto] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const canManage = roles.includes("superAdmin") || roles.includes("auctionAdmin"); const isParticipant = roles.includes("participant");

  useEffect(() => { if (loading) return; if (!user) { router.replace("/login"); return; } void (async () => { try { const token = await user.getIdToken(true); const me = await fetch("/api/me", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const profile = await me.json(); if (!me.ok) throw new Error(profile.error); const nextRoles = Array.isArray(profile.roles) ? profile.roles : []; setRoles(nextRoles); if (nextRoles.includes("participant")) { const response = await fetch("/api/me/auctions", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAuctions(data.auctions ?? []); } if (nextRoles.includes("superAdmin") || nextRoles.includes("auctionAdmin")) { const response = await fetch("/api/players", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const data = await response.json(); if (response.ok) setParticipants(data.players ?? []); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to load participants."); } })(); }, [loading, user, router]);

  async function createAccount() { if (!user) return; setError(""); setNotice(""); if (!name.trim()) { setError("Name is required."); return; } if (!email.trim()) { setError("Email address is required."); return; } if (!expertise.trim()) { setError("Expertise is required."); return; } setBusy(true); try { const result = await createParticipantAccount(user, { name: name.trim(), email: email.trim(), expertise: expertise.trim(), photo }); setName(""); setEmail(""); setExpertise(""); setPhoto(null); const token = await user.getIdToken(true); const response = await fetch("/api/players", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const data = await response.json().catch(() => ({})); if (response.ok) setParticipants(data.players ?? []); setNotice(`Participant account created successfully as Viewer. Temporary password: ${result.temporaryPassword}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create participant account."); } finally { setBusy(false); } }
  async function logout() { await signOut(getFirebaseAuth()); router.replace("/login"); }

  if (loading || !user) return <main className={styles.loading}>Loading…</main>;
  return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>{isParticipant ? "Participant Portal" : "Participant Management"}</p><h1>{isParticipant ? "My Auctions" : "Participants"}</h1><p>{isParticipant ? "Only auctions in which you are registered are shown here." : "Create participant accounts and manage the registered participant directory."}</p></div><div className={styles.actions}><button onClick={() => router.push("/profile")}>My Profile</button><button onClick={logout}>Sign Out</button></div></header>{error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}{isParticipant ? <section className={styles.grid}>{auctions.length ? auctions.map((auction) => <article className={styles.card} key={auction.id}><div className={styles.cardTop}><h2>{auction.name}</h2><span>{auction.participantStatus ?? "assigned"}</span></div><dl>{auction.categoryName && <div><dt>Category</dt><dd>{auction.categoryName}</dd></div>}{auction.basePrice !== undefined && <div><dt>Base points</dt><dd>{auction.basePrice}</dd></div>}{auction.minimumBasePrice !== undefined && <div><dt>Minimum points</dt><dd>{auction.minimumBasePrice}</dd></div>}<div><dt>Auction status</dt><dd>{auction.status}</dd></div></dl></article>) : <div className={styles.empty}>You are not currently registered in any auctions.</div>}</section> : canManage ? <><section className={styles.card}><div><p className={styles.eyebrow}>New Participant</p><h2>Create participant account</h2><p>Every participant account starts with Viewer access and receives the temporary password 123456. The participant must change it on first login.</p></div><div className={styles.form}><label>NAME<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>EMAIL ADDRESS<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>EXPERTISE<input value={expertise} onChange={(e) => setExpertise(e.target.value)} required /></label><label>PROFILE PICTURE <span>(optional)</span><input type="file" accept="image/*" onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} /></label></div><div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={() => void createAccount()}>{busy ? "CREATING…" : "CREATE PARTICIPANT"}</button></div></section><section className={styles.grid}>{participants.map((participant) => <article className={styles.card} key={participant.id}><div className={styles.cardTop}><h2>{participant.displayName}</h2><span>Viewer</span></div><dl><div><dt>Account</dt><dd>{participant.userId ? "Registered user" : "Profile only"}</dd></div></dl></article>)}</section></> : <div className={styles.empty}>You do not have participant-management access. Participant-specific auctions will appear here when you are assigned to one.</div>}</main>;
}
