"use client";

import { useEffect, useState } from "react";
import { signOut } from "firebase/auth";
import { getFirebaseAuth } from "@/lib/firebase/client";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import styles from "./participant.module.css";

type RosterItem={id:string;name:string;category?:string;status:string};
type Auction={id:string;name:string;status:string;startAtMillis:number|null;endAtMillis:number|null;categoryName?:string;basePrice?:number;minimumBasePrice?:number;participantStatus?:string;initialPurse?:number;bidderStatus?:string;participants?:RosterItem[];bidders?:RosterItem[]};
type Participant={id:string;displayName:string;expertise:string;photoUrl?:string|null;userId?:string|null};

export default function ParticipantPage(){
  const{user,loading}=useAuth();const router=useRouter();
  const[role,setRole]=useState("");const[auctions,setAuctions]=useState<Auction[]>([]);const[participants,setParticipants]=useState<Participant[]>([]);const[editing,setEditing]=useState<string|null>(null);const[name,setName]=useState("");const[expertise,setExpertise]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
  useEffect(()=>{if(loading)return;if(!user){router.replace("/login");return;}void(async()=>{try{const token=await user.getIdToken(true);const me=await fetch("/api/me",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const profile=await me.json();if(!me.ok)throw new Error(profile.error);setRole(profile.role??"viewer");if(profile.role==="participant"){const r=await fetch("/api/me/auctions",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setAuctions(d.auctions??[]);}else if(profile.role==="bidder"){const r=await fetch("/api/me/bidder-auctions",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setAuctions(d.auctions??[]);}else{const r=await fetch("/api/participants",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setParticipants(d.participants??[]);}}catch(e){setError(e instanceof Error?e.message:"Unable to load participants.");}})();},[loading,user,router]);
  async function logout(){await signOut(getFirebaseAuth());router.replace("/login");}
  function beginEdit(item:Participant){setEditing(item.id);setName(item.displayName);setExpertise(item.expertise);setError("");setNotice("");}
  async function saveParticipant(id:string){if(!user||!name.trim()||!expertise.trim())return;setBusy(true);setError("");setNotice("");try{const token=await user.getIdToken(true);const r=await fetch("/api/participants",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({id,displayName:name.trim(),expertise:expertise.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error);setParticipants(v=>v.map(p=>p.id===id?{...p,displayName:d.displayName,expertise:d.expertise}:p));setEditing(null);setNotice("Participant updated successfully.");}catch(e){setError(e instanceof Error?e.message:"Unable to update participant.");}finally{setBusy(false);}}
  if(loading||!user)return <main className={styles.loading}>Loading…</main>;
  const isPersonal=role==="participant"||role==="bidder";
  return <main className={styles.shell}>
    <header className={styles.header}><div><p className={styles.eyebrow}>{isPersonal?(role==="bidder"?"Bidder Portal":"Participant Portal"):"Participant Directory"}</p><h1>{isPersonal?"My Auctions":"Participants"}</h1><p>{isPersonal?"Only auctions in which you are registered or assigned are shown here.":"All registered participants are available here for review and profile maintenance."}</p></div><div className={styles.actions}><button onClick={()=>router.push("/profile")}>My Profile</button><button onClick={logout}>Sign Out</button></div></header>
    {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
    {isPersonal?<>{!auctions.length&&!error?<div className={styles.empty}>{role==="bidder"?"You are not currently assigned as a bidder to any auction.":"You are not currently registered in any auctions."}</div>:<section className={styles.grid}>{auctions.map(a=><article className={styles.card} key={a.id}><div className={styles.cardTop}><h2>{a.name}</h2><span>{a.participantStatus??a.bidderStatus??"assigned"}</span></div><dl>{a.categoryName&&<div><dt>Category</dt><dd>{a.categoryName}</dd></div>}{a.basePrice!==undefined&&<div><dt>Base points</dt><dd>{a.basePrice}</dd></div>}{a.minimumBasePrice!==undefined&&<div><dt>Minimum points</dt><dd>{a.minimumBasePrice}</dd></div>}{a.initialPurse!==undefined&&<div><dt>Initial purse</dt><dd>{a.initialPurse}</dd></div>}<div><dt>Auction status</dt><dd>{a.status}</dd></div></dl>{role==="bidder"&&<><div className={styles.rosterBlock}><strong>Participants in this auction</strong>{a.participants?.length?<ul>{a.participants.map(p=><li key={p.id}>{p.name}{p.category?` · ${p.category}`:""}</li>)}</ul>:<p>No participants assigned yet.</p>}</div><div className={styles.rosterBlock}><strong>Other bidders</strong>{a.bidders?.filter(b=>b.id!==user.uid).length?<ul>{a.bidders.filter(b=>b.id!==user.uid).map(b=><li key={b.id}>{b.name}</li>)}</ul>:<p>No other bidders assigned.</p>}</div></>}</article>)}</section>}</>:<section className={styles.grid}>{participants.map(p=><article className={styles.card} key={p.id}>{editing===p.id?<div><label>NAME<input value={name} onChange={e=>setName(e.target.value)}/></label><label>EXPERTISE<input value={expertise} onChange={e=>setExpertise(e.target.value)}/></label><div className={styles.actions}><button disabled={busy} onClick={()=>void saveParticipant(p.id)}>Save</button><button disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></div>:<><div className={styles.cardTop}><h2>{p.displayName}</h2><button onClick={()=>beginEdit(p)}>Edit</button></div><dl><div><dt>Expertise</dt><dd>{p.expertise||"—"}</dd></div><div><dt>Account</dt><dd>{p.userId?"Registered user":"Profile only"}</dd></div></dl></>}</article>)}</section>}
  </main>;
}
