import { NextResponse } from "next/server";
import { getApps, initializeApp, applicationDefault } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore, Timestamp } from "firebase-admin/firestore";

function getAdminApp(){return getApps()[0]??initializeApp({credential:applicationDefault()});}
async function authorize(request:Request,auctionId:string){const h=request.headers.get("authorization");if(!h?.startsWith("Bearer "))throw new Error("AUTHENTICATION_REQUIRED");const a=getAdminApp();const decoded=await getAuth(a).verifyIdToken(h.slice(7),true);const db=getFirestore(a);const auction=await db.collection("auctions").doc(auctionId).get();if(!auction.exists)throw new Error("AUCTION_NOT_FOUND");const d=auction.data()!;if(decoded.superAdmin!==true&&!(Array.isArray(d.adminIds)&&d.adminIds.includes(decoded.uid)))throw new Error("INSUFFICIENT_PERMISSIONS");return{db,auction,uid:decoded.uid};}
function errorResponse(e:unknown,fallback:string){const m=e instanceof Error?e.message:fallback;const s=m==="AUTHENTICATION_REQUIRED"?401:m==="INSUFFICIENT_PERMISSIONS"?403:m==="AUCTION_NOT_FOUND"?404:500;return NextResponse.json({error:s===401?"Authentication required.":s===403?"You are not assigned to this auction.":s===404?"Auction not found.":fallback},{status:s});}
export async function GET(request:Request,context:{params:Promise<{auctionId:string}>}){try{const id=(await context.params).auctionId;const{db}=await authorize(request,id);const ref=db.collection("auctions").doc(id);const [bs,us,ts]=await Promise.all([ref.collection("bidders").orderBy("createdAt").get(),db.collection("users").where("role","==","bidder").get(),ref.collection("teams").orderBy("createdAt").get()]);const bidders=bs.docs.map(d=>{const x=d.data();return{id:d.id,userId:x.userId,displayName:x.displayName,teamId:x.teamId??null,initialPurse:Number(x.initialPurse??0),spentPurse:Number(x.spentPurse??0),status:x.status??"active",createdAtMillis:x.createdAt?.toMillis?.()??0,updatedAtMillis:x.updatedAt?.toMillis?.()??0};});const assigned=new Set(bidders.map(x=>x.userId));const availableUsers=us.docs.filter(d=>!assigned.has(d.id)).map(d=>({userId:d.id,displayName:String(d.data().displayName??d.data().name??""),email:String(d.data().email??"")})).sort((a,b)=>a.displayName.localeCompare(b.displayName));const teams=ts.docs.map(d=>({id:d.id,name:String(d.data().name??""),initialPurse:Number(d.data().initialPurse??0),spentPurse:Number(d.data().spentPurse??0),active:d.data().active!==false}));return NextResponse.json({bidders,availableUsers,teams});}catch(e){return errorResponse(e,"Unable to load auction bidders.");}}
export async function POST(request:Request,context:{params:Promise<{auctionId:string}>}){try{const id=(await context.params).auctionId;const{db,uid}=await authorize(request,id);const b=await request.json();const userId=typeof b.userId==="string"?b.userId.trim():"";const initialPurse=Number(b.initialPurse);const teamId=b.teamId?String(b.teamId).trim():null;if(!userId)return NextResponse.json({error:"Bidder is required."},{status:400});if(!Number.isFinite(initialPurse)||initialPurse<0)return NextResponse.json({error:"Initial purse must be a non-negative number."},{status:400});const user=await db.collection("users").doc(userId).get();if(!user.exists||user.data()?.role!=="bidder")return NextResponse.json({error:"Select a registered bidder account."},{status:400});const ref=db.collection("auctions").doc(id);if(teamId&&!((await ref.collection("teams").doc(teamId).get()).exists))return NextResponse.json({error:"Selected team does not exist."},{status:400});const duplicate=await ref.collection("bidders").where("userId","==",userId).limit(1).get();if(!duplicate.empty)return NextResponse.json({error:"This bidder is already assigned to the auction."},{status:409});const now=Timestamp.now();const data=user.data()!;const out=await ref.collection("bidders").add({userId,displayName:String(data.displayName??data.name??data.email??"Bidder"),teamId,initialPurse,spentPurse:0,status:"active",createdAt:now,updatedAt:now,createdBy:uid});return NextResponse.json({id:out.id},{status:201});}catch(e){return errorResponse(e,"Unable to add bidder to this auction.");}}
export async function PATCH(request:Request,context:{params:Promise<{auctionId:string}>}){try{const id=(await context.params).auctionId;const{db}=await authorize(request,id);const b=await request.json();const bidderId=String(b.bidderId??"").trim();if(!bidderId)return NextResponse.json({error:"Bidder is required."},{status:400});const ref=db.collection("auctions").doc(id).collection("bidders").doc(bidderId);const snap=await ref.get();if(!snap.exists)return NextResponse.json({error:"Bidder assignment not found."},{status:404});const cur=snap.data()!;const update:Record<string,unknown>={updatedAt:Timestamp.now()};if(b.status==="active"||b.status==="inactive")update.status=b.status;if(b.teamId!==undefined){const teamId=b.teamId?String(b.teamId).trim():null;if(teamId&&!(await db.collection("auctions").doc(id).collection("teams").doc(teamId).get()).exists)return NextResponse.json({error:"Selected team does not exist."},{status:400});update.teamId=teamId;}if(b.initialPurse!==undefined){const n=Number(b.initialPurse);if(!Number.isFinite(n)||n<Number(cur.spentPurse??0))return NextResponse.json({error:"Initial purse cannot be below spent purse."},{status:400});update.initialPurse=n;}await ref.update(update);return NextResponse.json({id:bidderId});}catch(e){return errorResponse(e,"Unable to update auction bidder.");}}
export async function DELETE(request:Request,context:{params:Promise<{auctionId:string}>}){try{const id=(await context.params).auctionId;const{db}=await authorize(request,id);const bidderId=new URL(request.url).searchParams.get("bidderId")?.trim();if(!bidderId)return NextResponse.json({error:"Bidder is required."},{status:400});const ref=db.collection("auctions").doc(id).collection("bidders").doc(bidderId);if(!(await ref.get()).exists)return NextResponse.json({error:"Bidder assignment not found."},{status:404});await ref.delete();return NextResponse.json({ok:true});}catch(e){return errorResponse(e,"Unable to remove auction bidder.");}}
