"use client";
import { useCallback,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import styles from "../../auctions.module.css";
type Team={id:string;name:string;bidderId:string|null;initialPurse:number;spentPurse:number;minSquadSize:number;maxSquadSize:number;active:boolean};
type Bidder={id:string;displayName:string;teamId:string|null;initialPurse:number;spentPurse:number};
export default function TeamsPage(){const{user,loading}=useAuth();const p=useParams<{auctionId:string}>();const router=useRouter();const id=p.auctionId;const[teams,setTeams]=useState<Team[]>([]);const[bidders,setBidders]=useState<Bidder[]>([]);const[name,setName]=useState("");const[purse,setPurse]=useState("1000");const[min,setMin]=useState("0");const[max,setMax]=useState("20");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
const load=useCallback(async()=>{if(!user)return;const t=await user.getIdToken(true);try{const [tr,br]=await Promise.all([fetch(`/api/auctions/${id}/teams`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch(`/api/auctions/${id}/bidders`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})]);const a=await tr.json(),b=await br.json();if(!tr.ok)throw new Error(a.error||"Unable to load teams.");setTeams(a.teams??[]);setBidders(b.bidders??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load teams.");}},[user,id]);
useEffect(()=>{if(!loading&&user){const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);}},[loading,user,load]);
async function create(){if(!user)return;setBusy(true);setError("");setNotice("");try{const t=await user.getIdToken(true);const r=await fetch(`/api/auctions/${id}/teams`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name,initialPurse:Number(purse),minSquadSize:Number(min),maxSquadSize:Number(max)})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to create team.");setName("");await load();setNotice("Team created.");}catch(e){setError(e instanceof Error?e.message:"Unable to create team.");}finally{setBusy(false);}}
async function update(team:Team,patch:Record<string,unknown>){if(!user)return;setBusy(true);setError("");try{const t=await user.getIdToken(true);const r=await fetch(`/api/auctions/${id}/teams`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({teamId:team.id,...patch})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to update team.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update team.");}finally{setBusy(false);}}
if(loading||!user)return <main className={styles.loading}>Loading teams…</main>;
return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>Auction Platform / Auction Setup</p><h1>Teams & Squads</h1><p className={styles.subtitle}>Configure team identities, bidder ownership, purses and squad limits.</p></div><button className={styles.secondaryButton} onClick={()=>router.push("/auctions")}>Back</button></header>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
<section className={styles.editor}><section className={styles.configSection}><div className={styles.configHeader}><div><p className={styles.eyebrow}>Team setup</p><h2>Create team</h2></div></div><div className={styles.formGrid}><label>TEAM NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Lahore Lions"/></label><label>INITIAL PURSE<input type="number" min="0" value={purse} onChange={e=>setPurse(e.target.value)}/></label><label>MIN SQUAD<input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)}/></label><label>MAX SQUAD<input type="number" min="1" value={max} onChange={e=>setMax(e.target.value)}/></label></div><button className={styles.primaryButton} disabled={busy||!name.trim()} onClick={()=>void create()}>CREATE TEAM</button></section>
<section className={styles.configSection}><div className={styles.configHeader}><div><p className={styles.eyebrow}>Configured teams</p><h2>Teams</h2></div></div>{teams.length===0?<div className={styles.empty}>No teams configured yet.</div>:<div className={styles.configList}>{teams.map(team=><div className={styles.configRow} key={team.id}><div><strong>{team.name}</strong><small>Purse {team.initialPurse-team.spentPurse} remaining · Squad {team.minSquadSize}–{team.maxSquadSize} · {team.active?"Active":"Inactive"}</small></div><div className={styles.rowActions}><select value={team.bidderId??""} onChange={e=>void update(team,{bidderId:e.target.value||null})}><option value="">No bidder</option>{bidders.map(b=><option key={b.id} value={b.id}>{b.displayName}</option>)}</select><button className={styles.statusButton} disabled={busy} onClick={()=>void update(team,{active:!team.active})}>{team.active?"DEACTIVATE":"ACTIVATE"}</button></div></div>)}</div>}</section></section></main>}