"use client";

import Link from "next/link";
import { signOut } from "firebase/auth";
import { getFirebaseAuth } from "@/lib/firebase/client";
import { useAuth } from "@/components/auth-provider";
import { MobileNavigation } from "@/components/mobile-navigation";
import { useRouter } from "next/navigation";

const featureCards=[
{title:"Auctions",description:"Create, configure, schedule and manage league auctions.",icon:"gavel",href:"/auctions",adminOnly:true},
{title:"Participants",description:"Register and manage players and auction participation.",icon:"people",href:"/participant",participantAccess:true},
{title:"Bidding",description:"Enter assigned live auctions and place server-validated bids.",icon:"gavel",href:"/bidder",bidderAccess:true},
{title:"Teams & squads",description:"Configure team ownership, purses and roster limits.",icon:"shield",href:"/auctions",adminOnly:true},
{title:"Administration",description:"Manage global Auction Admin access and platform controls.",icon:"document",href:"/admin",superOnly:true}
];
function FeatureIcon({name}:{name:string}){if(name==="people")return <svg viewBox="0 0 48 48"><circle cx="24" cy="16" r="6"/><path d="M13 36c0-6 4.8-10 11-10s11 4 11 10M10 27c-3.5.8-6 3.5-6 7m34-7c3.5.8 6 3.5 6 7M9 18a5 5 0 1 0 0 10m30-10a5 5 0 1 1 0 10"/></svg>;if(name==="shield")return <svg viewBox="0 0 48 48"><path d="M24 5l15 6v10c0 10-6.5 17.5-15 22-8.5-4.5-15-12-15-22V11l15-6z"/><path d="M17 24l5 5 10-11"/></svg>;return <svg viewBox="0 0 48 48"><path d="M11 10l27 27M37 10L10 37"/><path d="M16 8l-4 4 24 24 4-4zM8 40h32M14 35h20"/></svg>}
export default function HomePage(){const{user,roles}=useAuth();const router=useRouter();const admin=roles.includes("superAdmin")||roles.includes("auctionAdmin");const participant=admin||roles.includes("participant");const bidder=roles.includes("bidder");async function logout(){await signOut(getFirebaseAuth());router.replace("/login");}const cards=featureCards.filter(f=>!user?false:f.superOnly?roles.includes("superAdmin"):f.adminOnly?admin:f.participantAccess?participant:f.bidderAccess?bidder:true);return <main className="home-shell"><header className="site-header"><Link className="brand" href="/" aria-label="Auction Platform home"><span className="brand-mark">AP</span><span className="brand-name"><strong>AUCTION</strong><strong>PLATFORM</strong></span></Link><nav className="site-nav"><Link className="active" href="/">Home</Link>{user&&admin?<Link href="/auctions">Auctions</Link>:null}{user&&bidder?<Link href="/bidder">Bidding</Link>:null}</nav><MobileNavigation authenticated={Boolean(user)} roles={roles} displayName={user?.displayName} email={user?.email} onSignOut={()=>void logout()}/></header><section className="hero-section"><div className="hero-content-stack"><div className="hero-copy"><p className="section-kicker">Auction Platform</p><h1>Configurable auction<br className="desktop-break"/> platform for leagues</h1><span className="gold-rule"/><p className="hero-description">Enterprise auction management for leagues, participants, teams, live bidding and post-auction validation.</p></div><section className="feature-section" aria-label="Platform actions" style={{maxWidth:"none",margin:"28px 0 0",padding:0}}><div className="feature-grid" style={{gridTemplateColumns:"1fr",padding:0,border:0,gap:12}}>{cards.map(f=><article className="feature-card feature-card-active" key={f.title} style={{minHeight:118,padding:"18px 20px",display:"grid",gridTemplateColumns:"64px minmax(0,1fr) auto",alignItems:"center",gap:18,textAlign:"left"}}><div className="feature-icon" style={{width:64,height:64,marginBottom:0}}><FeatureIcon name={f.icon}/></div><div><h2 style={{marginBottom:6}}>{f.title}</h2><p>{f.description}</p></div><Link className="coming-soon" href={f.href} style={{marginTop:0,whiteSpace:"nowrap"}}>Open <b>→</b></Link></article>)}</div></section></div></section><footer className="site-footer"><span>© 2026 Auction Platform. All rights reserved.</span><span>Privacy Policy&nbsp; | &nbsp;Terms of Service</span></footer></main>}
