"use client";

import { useEffect, useState } from "react";
import { EmailAuthProvider, reauthenticateWithCredential, updatePassword, updateProfile } from "firebase/auth";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { getFirebaseAuth, getFirebaseStorage } from "@/lib/firebase/client";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import styles from "./profile.module.css";

type Profile = { name: string; email: string; photoUrl: string | null; expertise: string; role: string; emailVerified: boolean; mustChangePassword: boolean };

export default function ProfilePage() {
  const { user, loading } = useAuth(); const router = useRouter(); const [profile, setProfile] = useState<Profile | null>(null); const [name, setName] = useState(""); const [expertise, setExpertise] = useState(""); const [photo, setPhoto] = useState<File | null>(null); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function token() { const current = getFirebaseAuth().currentUser; if (!current) throw new Error("Please sign in again."); return current.getIdToken(true); }
  async function load() { const response = await fetch("/api/me", { headers: { Authorization: `Bearer ${await token()}` }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load profile."); setProfile(data); setName(data.name); setExpertise(data.expertise ?? ""); }
  useEffect(() => { if (!loading && user) void load().catch((e) => setError(e instanceof Error ? e.message : "Unable to load profile.")); }, [loading, user]);
  async function saveProfile() { setBusy(true); setError(""); setMessage(""); try { let photoUrl = profile?.photoUrl ?? null; if (photo) { if (!photo.type.startsWith("image/")) throw new Error("Profile picture must be an image."); if (photo.size > 5 * 1024 * 1024) throw new Error("Profile picture must be 5 MB or smaller."); const current = getFirebaseAuth().currentUser!; const snapshot = await uploadBytes(ref(getFirebaseStorage(), `users/${current.uid}/profile-${Date.now()}-${photo.name}`), photo, { contentType: photo.type }); photoUrl = await getDownloadURL(snapshot.ref); } const current = getFirebaseAuth().currentUser!; await updateProfile(current, { displayName: name.trim(), photoURL: photoUrl }); const response = await fetch("/api/me", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ displayName: name.trim(), expertise: expertise.trim(), photoUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to save profile."); setProfile(data); setPhoto(null); setMessage("Profile updated successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save profile."); } finally { setBusy(false); } }
  async function changePassword() { if (!newPassword || newPassword.length < 6) { setError("New password must be at least 6 characters."); return; } if (newPassword !== confirmPassword) { setError("New passwords do not match."); return; } setBusy(true); setError(""); setMessage(""); try { const current = getFirebaseAuth().currentUser; if (!current?.email) throw new Error("Password change is unavailable for this account."); await reauthenticateWithCredential(current, EmailAuthProvider.credential(current.email, currentPassword)); await updatePassword(current, newPassword); const response = await fetch("/api/me", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ passwordChanged: true }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to update account state."); setProfile(data); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage("Password changed successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to change password. If your session is old, sign in again and retry."); } finally { setBusy(false); } }
  if (loading || !user) return <main className={styles.loading}>Loading profile…</main>;
  return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>Account</p><h1>My Profile</h1><p>Manage your personal information and account security. Your role and permissions are controlled by the platform.</p></div><button className={styles.secondary} onClick={() => router.push("/")}>Back</button></header>
    {profile?.mustChangePassword && <div className={styles.notice}><strong>Temporary password detected.</strong> Please change your password before using the account normally.</div>}
    <section className={styles.card}><div className={styles.identity}><div className={styles.avatar}>{profile?.photoUrl ? <img src={profile.photoUrl} alt="Profile" /> : <span>{(name || user.email || "U").slice(0,1).toUpperCase()}</span>}</div><div><h2>{name || user.email}</h2><span className={styles.role}>{profile?.role === "superAdmin" ? "SUPER ADMIN" : (profile?.role ?? "USER").replace(/([A-Z])/g," $1").toUpperCase()}</span></div></div><div className={styles.form}><label>NAME<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>EMAIL<input value={profile?.email ?? user.email ?? ""} readOnly /></label><label>EXPERTISE<input value={expertise} onChange={(e) => setExpertise(e.target.value)} placeholder="Optional" /></label><label>PROFILE PICTURE<input type="file" accept="image/*" onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} /></label></div><div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={saveProfile}>{busy ? "SAVING…" : "SAVE PROFILE"}</button></div></section>
    <section className={styles.card}><div><p className={styles.eyebrow}>Security</p><h2>Change password</h2><p className={styles.help}>For security, enter your current password before choosing a new one.</p></div><div className={styles.form}><label>CURRENT PASSWORD<input type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label>NEW PASSWORD<input type="password" autoComplete="new-password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><label>CONFIRM NEW PASSWORD<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /></label></div><div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={changePassword}>{busy ? "UPDATING…" : "CHANGE PASSWORD"}</button></div></section>
    {error && <div className={styles.error} role="alert">{error}</div>}{message && <div className={styles.notice} role="status">{message}</div>}
  </main>;
}
