"use client";
import {useCallback,useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {useAuth} from "@/components/auth-provider";
import styles from "../../auctions.module.css";
type P={id:string;playerId:string;playerName:string;categoryId:string;categoryName:string;status:string;basePrice:number};
type L={id:string;playerName:string;startingBid:number;bidIncrement:number;status:string;sortOrder:number};
export default function LotsPage(){const{user,loading}=useAuth();const p=useParams<{auctionId:string}>();const router=useRouter();const id=p.auctionId;const[participants,setParticipants]=useState<P[]>([]);const[lots,setLots]=useState<L[]>([]);const[playerId,setPlayerId]=useState("");const[start,setStart]=useState("100");const[increment,setIncrement]=useState("10");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
const load=useCallback(async()=>{if(!user)return;try{const t=await user.getIdToken(true);const [pr,lr]=await Promise.all([fetch(`/api/auctions/${id}/participants`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch(`/api/auctions/${id}/lots`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})]);const a=await pr.json(),b=await lr.json();if(!pr.ok)throw new Error(a.error||"Unable to load participants.");if(!lr.ok)throw new Error(b.error||"Unable to load lots.");setParticipants((a.participants??[]).filter((x:P)=>x.status==="eligible"));setLots(b.lots??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load lots.");}},[user,id]);useEffect(()=>{if(!loading&&user)void load();},[loading,user,load]);
async function create(){if(!user||!playerId)return;setBusy(true);setError("");setNotice("");try{const t=await user.getIdToken(true);const p=participants.find(x=>x.playerId===playerId);const r=await fetch(`/api/auctions/${id}/lots`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({playerId,categoryId:p?.categoryId,startingBid:Number(start),bidIncrement:Number(increment)})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to create lot.");setPlayerId("");await load();setNotice("Lot added to queue.");}catch(e){setError(e instanceof Error?e.message:"Unable to create lot.");}finally{setBusy(false);}}
if(loading||!user)return <main className={styles.loading}>Loading lots…</main>;
return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>Auction Platform / Live Auction</p><h1>Lot Management</h1><p className={styles.subtitle}>Prepare the auction queue, starting bids and increments before going live.</p></div><div className={styles.headerActions}><button className={styles.secondaryButton} onClick={()=>router.push(`/live/${id}`)}>Live Room</button><button className={styles.secondaryButton} onClick={()=>router.push("/auctions")}>Back</button></div></header>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<section className={styles.editor}><section className={styles.configSection}><div className={styles.configHeader}><div><p className={styles.eyebrow}>Auction setup</p><h2>Add lot</h2></div></div><div className={styles.formGrid}><label>ELIGIBLE PARTICIPANT<select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Select participant</option>{participants.map(x=><option key={x.playerId} value={x.playerId}>{x.playerName} — {x.categoryName}</option>)}</select></label><label>STARTING BID<input type="number" min="0" value={start} onChange={e=>setStart(e.target.value)}/></label><label>BID INCREMENT<input type="number" min="1" value={increment} onChange={e=>setIncrement(e.target.value)}/></label></div><button className={styles.primaryButton} disabled={busy||!playerId} onClick={()=>void create()}>ADD TO QUEUE</button></section><section className={styles.configSection}><div className={styles.configHeader}><div><p className={styles.eyebrow}>Queue</p><h2>{lots.length} lots</h2></div></div>{lots.length===0?<div className={styles.empty}>No lots queued yet.</div>:<div className={styles.configList}>{lots.map((x,i)=><div className={styles.configRow} key={x.id}><div><strong>{i+1}. {x.playerName}</strong><small>Starting {x.startingBid} · Increment {x.bidIncrement} · {x.status}</small></div></div>)}</div>}</section></section></main>
}
